### ISSUE TITLE
功能请求 能否给 CapsLock 添加 alone 模式, 使单按 CapsLock 时, 触发 Esc 或者其他键

### ISSUE THREAD

**Issue by toure00** [xianyukang/MyKeymap#187]
大佬你好, 我在 linux 上用的按键映射工具 xremap 中, 有这样的功能, 配置如下:
``` yaml
modmap:
  - name: Global
    remap: 
      # Dispatch different keys depending on whether you hold it or press it alone
      CapsLock:
        held:  Ctrl_L
        alone: Esc
        alone_timeout_millis: 1000
```
作用是给 capslock 映射两个键, 如果是组合键, CapsLock 当修饰键, 就发送 LCtrl , 如果只按一下, 就发送 Esc , MyKeymap 可以实现类似的功能吗
